name: mini-project

dependencies:
  # Base dependencies
  - python=3.7
  - pip
  # Numerical
  - numpy
  - scipy
  # Visualization
  - matplotlib
  - seaborn
  - pandas
  # Image processing
  - pillow
  - scikit-image
  - opencv-python
  - pip:
      # Animation
      - imageio
      - imageio-ffmpeg
      # Others
      - tqdm
      - peakutils
